### ISSUE TITLE
List view error after update to 9.5.14

### ISSUE THREAD

**Issue by Balindil** [georgringer/news#1166]
After the update to TYPO3 9.5.14 suddenly two of three overview pages (list view) of the news no longer work. Although all three are set identically, except for the selected category.

This is the message:
`
Parameter "acec1fc0ac7e1adfbcd522115dc0792" for route "tx_news_pi1_3" must match "[^/]++" ("" given) to generate a corresponding URL.
`

**Comment by chesio** [comment]
Perhaps related: https://stackoverflow.com/questions/54948296/routeenhancer-with-aspects-throws-invalidparameterexception

**Comment by Balindil** [comment]
I have checked this. There are no news entries with empty title or path segments with slash in it. This is not the same problem. In 9.5.13 everything is also ok.

**Comment by burdin-an** [comment]
If in "routeEnhancers" I will make "default: '/' "
To me gives an error message!
If in "routeEnhancers" I will make "default:" "
There is no mistake!

I have the following URL everywhere(1234 - uid news):
https://examples.net/page/
https://examples.net/news/
https://examples.net/news/1234/ 

My config.yml:
```
base: 'https://example.net/'
baseVariants: {  }
errorHandling: {  }
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: '/'
    index: ''
    map:
      '/': 0
      'sitemap.xml': 1533906435
  NewsPlugin:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/'
        _controller: 'News::list'
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      # Date year:
      - routePath: '/{year}'
        _controller: 'News::list'
        _arguments:
          month: 'overwriteDemand/month'
          year: 'overwriteDemand/year'
        requirements:
          year: '\d+'
      # Date year/month:
      - routePath: '/{year}/{month}'
        _controller: 'News::list'
        _arguments:
          month: 'overwriteDemand/month'
          year: 'overwriteDemand/year'
        requirements:
          month: '\d+'
          year: '\d+'
    defaultController: 'News::list'
    defaults:
      year: ''
      month: ''
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: uid
      category:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: title
      tag_name:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_tag
        routeFieldName: title
      year:
        type: StaticRangeMapper
        start: '1970'
        end: '2099'
      month:
        type: StaticRangeMapper
        start: '01'
        end: '12'
```

**Comment by Balindil** [comment]
Even if I try routeEnhancers default:'' there is the same error. I think my config.yaml is a bit too complicated. Is there any way to simplify it?

This is my config.yaml:

```

base: 'https://www.example.de/'
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: ''
    hreflang: de-DE
    direction: ltr
    flag: de
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    suffix: /
    index: ''
    map:
      /: 0
      banners.html: 9001
      bannerclick.html: 9002
  NewsList:
    type: Plugin
    limitToPages:
      - 4
      - 5
      - 6
    routePath: '/page/{@widget_0/currentPage}'
    namespace: tx_news_pi1
    aspects:
      '@widget_0/currentPage':
        type: StaticRangeMapper
        start: '1'
        end: '20'
  NewsDetail:
    type: Extbase
    limitToPages:
      - 39
      - 40
      - 41
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    defaultController: 'News::detail'
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
  DateMenu:
    type: Extbase
    limitToPages:
      - 4
      - 5
      - 6
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/dateFilter/{date-year}'
        _controller: 'News::list'
        _arguments:
          date-month: overwriteDemand/month
          date-year: overwriteDemand/year
          page: '@widget_0/currentPage'
        requirements:
          date-year: \d+
      -
        routePath: '/dateFilter/{date-year}/page/{page}'
        _controller: 'News::list'
        _arguments:
          date-year: overwriteDemand/year
          page: '@widget_0/currentPage'
        requirements:
          date-year: \d+
          page: \d+
      -
        routePath: '/dateFilter/{date-year}/{date-month}'
        _controller: 'News::list'
        _arguments:
          date-month: overwriteDemand/month
          date-year: overwriteDemand/year
          page: '@widget_0/currentPage'
        requirements:
          date-month: \d+
          date-year: \d+
      -
        routePath: '/dateFilter/{date-year}/{date-month}/page/{page}'
        _controller: 'News::list'
        _arguments:
          date-month: overwriteDemand/month
          date-year: overwriteDemand/year
          page: '@widget_0/currentPage'
        requirements:
          date-month: \d+
          date-year: \d+
          page: \d+
    defaultController: 'News::list'
    defaults:
      date-month: ''
      date-year: ''
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '20'
      date-month:
        type: StaticValueMapper
        map:
          '01': '01'
          '02': '02'
          '03': '03'
          '04': '04'
          '05': '05'
          '06': '06'
          '07': '07'
          '08': '08'
          '09': '09'
          '10': '10'
          '11': '11'
          '12': '12'
      date-year:
        type: StaticRangeMapper
        start: '2000'
        end: '2030'
routes:
  -
    route: robots.txt
    type: staticText
    content: "...some configuration..."

```

**Comment by burdin-an** [comment]
and you turn off page pagination and there will be no error.
![news-pagination](https://user-images.githubusercontent.com/6196844/75652715-ea68f280-5caf-11ea-8911-24fa940a2a61.png)

**Comment by burdin-an** [comment]
I have:
date-month:
  type: StaticRangeMapper
        start: '01'
        end: '12'

**Comment by Balindil** [comment]
You're right. If I hide the pagination the error is gone. But then number of items per page will be ignored. There are too many. Pagination is necessary.

**Comment by burdin-an** [comment]
I have the same problem.
I'm trying to solve, but so far it’s not working out.
We probably need help from the developer.

**Comment by jloderhose** [comment]
Hi guys,
one key to the solution lies in a single but heavy weighting line in the TYPO3 9.5.14 ChangeLog

> TYPO3's Route Enhancers now support "optional defaults" and correctly evaluate "default" and "requirements" options,....

The "defaults" in the site config did not have any effects until now. That changed with the latest TYPO3 update and now defaults are defaults. They overwrite any value passed to the respective parameters. So with 

<pre>defaults:
  date-month: ''
  date-year: ''</pre>

overwriteDemand/year and overwriteDemand/month will always be the empty string, thus causing the error message

> ("" given)

Additionally, I recommend to drop the StaticValueMapper for date-month since it maps identical values in your example and to clean the "routePaths off of unused "_arguments".

<pre>routePath: '/dateFilter/{date-year}'</pre>

will never use "overwriteDemand/month" in

<pre>_arguments:
  date-month: overwriteDemand/month
  date-year: overwriteDemand/year</pre>

Hope, this helps! It did for me.

**Comment by Balindil** [comment]
Thank you @jloderhose! I have my config.yaml rewritten and now it works.

This is the new config.yaml:
```yaml
base: 'https://www.example.de/'
baseVariants: {  }
errorHandling: {  }
languages:
  - title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: ''
    hreflang: de-DE
    direction: ltr
    flag: de
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    suffix: /
    index: ''
    map:
      /: 0
      banners.html: 9001
      bannerclick.html: 9002
  News-List:
    type: Extbase
    extension: News
    plugin: Pi1
    limitToPages:
      - 4
      - 5
      - 6
    routes:
      - routePath: '/page/{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
        requirements:
          page: '\d+'
      - routePath: '/dateFilter/{date-year}'
        _controller: 'News::list'
        _arguments:
          date-year: 'overwriteDemand/year'
        requirements:
          date-year: '\d+'
      - routePath: '/dateFilter/{date-year}/page/{page}'
        _controller: 'News::list'
        _arguments:
          date-year: 'overwriteDemand/year'
          page: '@widget_0/currentPage'
        requirements:
          date-year: '\d+'
          page: '\d+'
      - routePath: '/dateFilter/{date-year}/{date-month}'
        _controller: 'News::list'
        _arguments:
          date-month: 'overwriteDemand/month'
          date-year: 'overwriteDemand/year'
        requirements:
          date-month: '\d+'
          date-year: '\d+'
      - routePath: '/dateFilter/{date-year}/{date-month}/page/{page}'
        _controller: 'News::list'
        _arguments:
          date-month: 'overwriteDemand/month'
          date-year: 'overwriteDemand/year'
          page: '@widget_0/currentPage'
        requirements:
          date-month: '\d+'
          date-year: '\d+'
          page: '\d+'
    defaultController: 'News::list'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      date-month:
        type: StaticRangeMapper
        start: '01'
        end: '12'
      date-year:
        type: StaticRangeMapper
        start: '2000'
        end: '2030'
  News-Detail:
    type: Extbase
    extension: News
    plugin: Pi1
    limitToPages:
      - 39
      - 40
      - 41
    routes:
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    defaultController: 'News::detail'
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
routes:
  - route: robots.txt
    type: staticText
    content: "...some configuration..."
```
