### ISSUE TITLE
routeEnhancers not working anymore: 404 Error on Detail Page / 404 on Category Filter

### ISSUE THREAD

**Issue by bh-teufels** [georgringer/news#1248]
## Bug Report

**Current Behavior**
The routeEnhancers not working correctly anymore. 
It throws 404-Error on Detail Page and Category Menu

**Expected behavior/output**
Showing Detail-Page with speaking URL and List with Category Filter

**Environment**
- TYPO3 version(s): 9.5.16
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Additional context**
used the Basic Setup from (https://docs.typo3.org/p/georgringer/news/8.1/en-us/AdministratorManual/BestPractice/Routing/Index.html) 
Worked with Typo3 9.5.14

Here the used routeEnhancer
```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    map:
      /: 0
      .ajax: 500
      rss.feed: 9818
      sitemap.xml: 1533906435
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: /
        _controller: 'News::list'
      -
        routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      -
        routePath: '/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      -
        routePath: '/{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      tag-name:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_tag
        routeFieldName: slug
```
