### ISSUE TITLE
Routing with Tag filter and Paginator don't work at the same time

### ISSUE THREAD

**Issue by aksenovaa** [georgringer/news#1378]
My project uses a tag-filtered list. The filtered list can contain several pages at the same time.
https://aksenovaa.ru/portfolio/

Routing for tags works great:
https://aksenovaa.ru/portfolio/tag-cifrovaja-pechat/
https://aksenovaa.ru/portfolio/tag-dizain-poligrafii/

Routing news list pages without filtering by tags also works great.
https://aksenovaa.ru/portfolio/page-2/
https://aksenovaa.ru/portfolio/page-3/
Although not everything is in order here with page 1
The link to it turns out to be a broken line:
This is how it works if you remove
```
defaults:
        page: '1'
```
https://aksenovaa.ru/portfolio/?tx_news_pi1%5Baction%5D=list&tx_news_pi1%5Bcontroller%5D=News&cHash=f33ba193a8437daa8bd4445d97568eee

If 
```
defaults:
        page: '1'
```
duplicates appear, this is the same page:
https://aksenovaa.ru/portfolio/page-1/
https://aksenovaa.ru/portfolio/
Can this be fixed?

But at the same time, when the news filtered by tags is split into pages - it does not work!
https://aksenovaa.ru/portfolio/tag-dizain-poligrafii/
and page 2:
https://aksenovaa.ru/portfolio/tag-dizain-poligrafii/?tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=2&cHash=a6ca69e78d72e1e6671890d3c670bece

Full customization
```
  News:
    type: Extbase
    # Limiting to pages with news extension
    limitToPages: [96,97,104,105]
    extension: News
    plugin: Pi1
    routes:
      # news
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news

      # Pagination
      - routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
      # categories
      - routePath: '/cat-{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      # tags
      - routePath: '/tag-{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags

      # tags+pagination
    #      - routePath: '/tag-{tag-name}/page-{page}'
    #          _controller: 'News::list'
    #          _arguments:
    #            tag-name: overwriteDemand/tags
    #            page: '@widget_0/currentPage'
    #          requirements:
    #            page: '\d+'
    defaultController: 'News::list'
    defaults:
        page: '1'
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      tag-name:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_tag
        routeFieldName: slug
```
Tried adding a piece like this:
```
      # tags+pagination
         - routePath: '/tag-{tag-name}/page-{page}'
            _controller: 'News::list'
            _arguments:
                tag-name: overwriteDemand/tags
                page: '@widget_0/currentPage'
              requirements:
                page: '\d+'
```
An error occurs and nothing works at all

**Comment by georgringer** [comment]
if still valid then this is a core issue

**Comment by tritumBj** [comment]
I am having this issue on a TYPO3 v10 with EXT:news 9.x.

@aksenovaa I have checked the above mentioned website. You have solved your problem. I know, it is running (now) on TYPO3 v11. How did you manage it?

Thank you for any input on this one :)

**Comment by aksenovaa** [comment]
> I am having this issue on a TYPO3 v10 with EXT:news 9.x.
> 
> @aksenovaa I have checked the above mentioned website. You have solved your problem. I know, it is running (now) on TYPO3 v11. How did you manage it?
> 
> Thank you for any input on this one :)
TYPO3 v11, Routs for News:
```

  News:
    type: Extbase
    limitToPages:
      - 6
      - 54
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      -
        routePath: '/cat-{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      -
        routePath: '/tag-{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
      -
        routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: 'currentPage'
      -
        routePath: '/tag-{tag-name}/page-{page}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
          page: 'currentPage'
    defaultController: 'News::list'
    defaults:
      page: '1'
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      tag-name:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_tag
        routeFieldName: slug
```
