### ISSUE TITLE
tx_news tag menu and TYPO3 9.5.25 causes routing error

### ISSUE THREAD

**Issue by nannione** [georgringer/news#1490]
## Bug Report

**Current Behavior**
Selecting the tag view in the plug-in causes an error in the frontend:
`(1/1) Symfony\Component\Routing\Exception\InvalidParameterException
Parameter "x85eb534ff5eab552f84c78a2eacc27" for route "tx_news_pi1_2" must match ".+" ("" given) to generate a corresponding URL.

in /..my_path_placeholder..../vendor/symfony/routing/Generator/UrlGenerator.php line 193`

**Expected behavior/output**
The output of a tag menu is expected

**Environment**
- TYPO3 version(s): 9.5.25
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: not OS related

**Possible Solution**
temporary solution / workaround: Editing the vendor file UrlGenerator.php line 193 manually

**Comment by christophlehmann** [comment]
Is your slug field in tag table empty?

**Comment by nannione** [comment]
No, the slug fields are are not empty.

**Comment by seirerman** [comment]
Just had the same error, but some slug fields in sys_category were indeed empty. Giving them a value and clearing the system cache fixed the issue for me.

@nannione , you might also check the category routeEnhancer in your config.yaml:
```
routeEnhancers:
  ...
  News:
    ...
    plugin: Pi1
    routes:
      ...
      - routePath: '/kategorie/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
    ...
    aspects:
      ...
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
```
