### ISSUE TITLE
Slug Behaviour: New option "omit check"

### ISSUE THREAD

**Issue by lorenzulrich** [georgringer/news#1520]
## Feature Request

The Slug Behaviour configuration ensures that there are no duplicate slugs, either in scope of the whole installation or in scope of a site. As a consequence, if a news record with the same title as an existing record is created, a suffix is added:

* awesome-news
* awesome-news-1
* awesome-news-2
 
etc.

However, non-unique slugs may not be a problem if the installation is ensuring the uniqueness of a route by adding the news uid as a suffix:

```yaml
routeEnhancers:
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    aspects:
      news-title:
        type: PersistedPatternMapper
        tableName: 'tx_news_domain_model_news'
        routeFieldPattern: '^(?P<path_segment>.+)-(?P<uid>\d+)$'
        routeFieldResult: '{path_segment}-{uid}'
```

This is a pattern commonly used e.g. in newspaper websites.

In TYPO3 8, there was no slug handling as it is now and uniqueness was not ensured. Therefore, without special manipulation, the same configuration is no longer possible.

I'm aware that I can just override the TCA settings of the `path_segment` field to return to the old behaviour, however I think it would be a nice option to have no uniqueness check in place at all.
