### ISSUE TITLE
Category filter without routeEnhancer throws exception

### ISSUE THREAD

**Issue by bavarianbytes** [georgringer/news#1658]
## Bug Report

**Current Behavior**
If a place a categories plugin for filtering on the same page as the list view plugin, the generated links to the categories are either:

1. throwing an exception if i don't define a routeEnhancer for categories, or
2. do not work cause of issue #1640

Cause of case 2. i use case 1. Here are the details:
The exception is:
```
(1/1) #1573047338 InvalidArgumentException
Argument $currentPageNumber must be greater than 0
```
Seems that the generated links via
```
<f:link.page pageUid="{settings.listPid}" additionalParams="{tx_news_pi1:{overwriteDemand:{categories: category.item.uid}}}">{category.item.title}</f:link.page>
```
(single filter), or
```
<f:link.page pageUid="{settings.listPid}" additionalParams="{n:multiCategoryLink.arguments(mode: 'add', item: filterId, list: overwriteDemand.categories)}">{category.item.title}</f:link.page>
```
(multi-filter)

have problems with paging. The paging routeEnhancer keyword `seite` ist used without a number. In my case the urls look like this:
`domain.de/news` (list view)
`domain.de/news/seite-2` (paged list view)
`domain.de/news/seite?tx_news_pi1%5BoverwriteDemand%5D%5Bcategories%5D=29&cHash=154fcbe5069cfdb109b73cd394e2f637` (generated link from category filter)

My site config:
```
    routes:
      - routePath: '/'
        _controller: 'News::list'
      -
        routePath: '/{page-label}-{page}'
        _controller: 'News::list'
        _arguments:
          page: 'currentPage'
      # -
      #   routePath: '/{category-name}'
      #   _controller: 'News::list'
      #   _arguments:
      #     category-name: overwriteDemand/categories
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      page-label:
        type: LocaleModifier
        default: seite
        localeMap:
...
```

**Expected behavior/output**
Generated category links should look like this:
`domain.de/news?tx_news_pi1%5BoverwriteDemand%5D%5Bcategories%5D=29&cHash=154fcbe5069cfdb109b73cd394e2f637`

**Environment**
- TYPO3 version(s): 10.4.18
- news version: 9.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: OSX
