### ISSUE TITLE
News 9.2.0: pagination doesn't work for tagged news pages

### ISSUE THREAD

**Issue by aksenovaa** [georgringer/news#1719]
## Bug Report

**Current Behavior**
When I use routing typo3's feature to rewrite URLs for tagged news pages, grouped by tags the pagination doesn't work. 
News list pages:
https://aksenovaa.ru/portfolio/

Pagination on list page:
https://aksenovaa.ru/portfolio/page-2/

Tagged news list page:
https://aksenovaa.ru/portfolio/tag-dizain/

But the link to the next page in the list of tagged news
https://aksenovaa.ru/portfolio/page-2/

**Expected behavior**
https://aksenovaa.ru/portfolio/tag-dizain/page-2/

**Environment**
- TYPO3 version: 10.4.24
- news version: 9.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Routing configuration**

```
 routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: '/'
    index: '/'
    map:
      '/': 0
      # EXT:news / RSS feed:
      feed.xml: 9818
      # EXT:seo / SEO sitemap:
      sitemap.xml: 1533906435
      # EXT:yoast_seo / snippet preview:
      yoast-snippetpreview.json: 1480321830
  News:
    type: Extbase
    limitToPages:
      - 96
      - 97
      - 104
      - 105
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      -
        routePath: '/cat-{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      -
        routePath: '/tag-{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
      -
        routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: 'currentPage'
#      -
#        routePath: '/tag-{tag-name}/page-{page}'
#        _controller: 'News::list'
#        _arguments:
#          tag-name: overwriteDemand/tags
#          page: 'currentPage'
    defaultController: 'News::list'
    defaults:
      page: '1'
    #      tag-name: ''
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      tag-name:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_tag
        routeFieldName: slug
```

**Comment by caplod** [comment]
I have a similar problem:

I have a Date Menu by year for news and have links like:
`/news/2019`

When I select no year pagination is working:
`/news/page-2`

But not when I am on year 2019 the link for page 2 is again:
`/news/page-2`

without route enhancers everything is working. 
`news?tx_news_pi1[controller]=News&tx_news_pi1[currentPage]=2&tx_news_pi1[overwriteDemand][year]=2019&cHash=...`

Environment

- TYPO3 version: 10.4.24
- news version: 9.2

```
routeEnhancers:
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/'
        _controller: 'News::list'
      # Pagination:
      - routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: 'currentPage'
        requirements:
          page: '\d+'
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      # Date year:
      - routePath: '/{date-year}'
        _controller: 'News::list'
        _arguments:
          date-year: 'overwriteDemand/year'
          page: 'currentPage'
        requirements:
          date-year: '\d+'
      # Date year + pagination:
      - routePath: '/{date-year}/page-{page}'
        _controller: 'News::list'
        _arguments:
          date-year: 'overwriteDemand/year'
          page: 'currentPage'
        requirements:
          date-year: '\d+'
          page: '\d+'
    defaultController: 'News::list'
    defaults:
      page: '0'
      date-year: ''
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '25'
      date-year:
        type: StaticRangeMapper
        start: '2000'
        end: '2030'
```
