### ISSUE TITLE
routeEnhancers with overwriteDemand/* not working in 12

### ISSUE THREAD

**Issue by trokohl** [georgringer/news#2146]
## Bug Report

I am not sure if it is a news or Typo3 bug. But since Typo 12 the mapping of the overwriteDemand parameters in combination with the NewsCategoryMapper or PersistedAliasMapper doesn't seem to work anymore.

**Current Behavior**
A call from 
news/testcat 

returns no results but a call with:

news/?tx_news_pi1[overwriteDemand][categories]=1&cHash=0e70fa1f6a2ce75e2db9713a4ddb5aeb

returns results. 
The array overwriteDemand always arrives in the controller with null in the first case.

**Environment**
- TYPO3 version(s): 12.4.x
- news version: 11.1.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

```

routeEnhancers:
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/'
        _controller: 'News::list'
      - routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: 'currentPage'
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      - routePath: '/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      - routePath: '/{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      news-title:
        type: NewsTitle
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      category-name:
        type: NewsCategory
      tag-name:
        type: NewsTag
  PageTypeSuffix:
    type: PageType
    map:
      'feed.xml': 9818
      'calendar.ical': 9819
```

**Comment by web2date** [comment]
Hi Georg, I can confirm that bug too in TYPO3v11 / news v 11.1.2 when overwriting stickylist via DateMenu. Kind regards Andrea

**Comment by georgringer** [comment]
tested this with simple
```yaml
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: ''
    map:
      feed.xml: 9818
      calendar.ical: 9819
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/'
        _controller: 'News::list'
      - routePath: '/category/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      - routePath: '/tag/{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
```

and looks good - imho the issue must be in core or ordering of routing :/
