### ISSUE TITLE
No items in list-view when "news-list incl. detail view" plugin and routing enabled

### ISSUE THREAD

**Issue by DrDBanner** [georgringer/news#2497]
## Bug Report

**Current Behavior**
I've got some issues with routes for categories (when "news-list incl. detail view"). 
If I leave the routing unconfigured, **all works as expected**.

```
Like https://staging.site.com/page-with-list-and-detail-plugin/?tx_news_pi1%5BoverwriteDemand%5D%5Bcategories%5D=8&cHash=b9173993bf9ba73cd81500135f548900
```

Now I add:

```
- routePath: '/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
```
and the URL becomes
`https://staging.site.com/page-with-list-and-detail-plugin/8/`

like expected and totally fine. Because I didn't add any aspects. For my understanding the aspect part is not relevant for the functionality, that's why I leave it out in this example. But in total, if I add the aspect, I get the final URL as desired but the list remains empty with the notification "Dieser Artikel ist nicht mehr verfügbar." 

BUT: **The list is empty and doesn't show any items when I have "news-list incl. detail view" plugin configured**. If I leave the plugin to "list-only" I get items listed. Obviously, I want to have the plugin with list and detail view.

This is the whole part of the configuration for now. 

```
routeEnhancers:
  News:
    type: Extbase
    limitToPages: [6,15]
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      - routePath: '/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      news:
        type: NewsTitle
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      tag:
        type: NewsTag 
```

For clarification: The list view shows items when I do not call any category URL's ...

**Expected behavior/output**
Having items listed within category slug when overwrite demand with "news-list incl. detail view" plugin configured. Alternatively, if it's just an configuration issue, some additions to the docs.

**Environment**
- TYPO3 version(s): 12.4.16
- news version: 11.4.2
- Is your TYPO3 installation set up with Composer (Composer Mode): YES
- OS: FreeBSD

**Comment by DrDBanner** [comment]
Changing the order makes it work:

```
routeEnhancers:
  News:
    type: Extbase
    limitToPages: [6, 15]
    extension: News
    plugin: Pi1
    routes:
      - routePath: "/{category}"
        _controller: "News::list"
        _arguments:
          category: overwriteDemand/categories
      - routePath: "/{news}"
        _controller: "News::detail"
        _arguments:
          news: news
      - routePath: "/"
        _controller: "News::list"
    defaultController: "News::list"
    defaults:
      page: ''
    aspects:
      news:
        type: NewsTitle
      page:
        type: StaticRangeMapper
        start: "1"
        end: "100"
      category:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
```
