### ISSUE TITLE
Commenting system for news based on the form framework without any other third party extension

### ISSUE THREAD

**Issue by HVStechnik** [georgringer/news#548]
Dear Typo3 news community,

This isn't an issue, it rather is a tutorial, which I propose to be added to the news documentation: I was having a hard time for years with implementing a simple, reliable and upgrade-safe commenting solution to tt_news and now to tx_news. There have been multiple extensions as timtab, ve_guestbook, comments, etc. for both news extensions. But most of them aren't supported any more or had significant security issues. 
I was looking for a Typo3 (Typoscript & Fluid) native solution to have a commenting section below each news entry. I would like to propose the following solution and check with all of you, whether there any
- Security Concerns
- Suggestions for improvements

What does it do?:
- Simple commenting function for the news extension: a form on each detailed news page and a list of comments below each detailed news entry
- Comment count available in the news list and detail view templates
- Lists comments in the backend 
- Sends email notification for new comments

How does it work?:
- Uses the Typo3 native form framework as a comment form
- Inserts the comments as content elements related to the respective news entry
 
Advantages:
- Runs without third party extensions (except for the news extension) >> no more unmaintained and incompatible extensions
- Highly customizable >> you'll find some potential additions (e.g.,  moderation of newly created comments, commenting by logged-in users only) in my comments below

To dos:
- Backend view of comments with room for improvements: I use the list view with a system folder
- Still requires a 4 lines non-update safe change to the form framework's SaveToDatabase finisher class (4 lines of code to be added after each Typo3 update in order to clear the cache after a new comment has been made >> If you have any other idea how to solve the issue, please let me know!)

In the following you'll the tutorial on how to achieve this:

First of all, save a new form template into one of your form allowedFileMounts folders (see here how to setup the form framework: https://docs.typo3.org/typo3cms/extensions/form/Concepts/FormFileStorages/Index.html - you have to create a .yaml file referencing to the allowedFileMounts path and than add this .yaml file to the TS setup: plugin.tx_form.settings.yamlConfigurations.100 = path_to/something.yaml). 

I name my form template file within the allowedFileMounts  folder "comment.yaml" and add the following content: (Note: YAML get's its structure from spaces, do not use tabs)

```
type: Form
identifier: news_comment
label: 'New comment'
renderingOptions:
  submitButtonLabel: Submit
  addQueryString: 1
prototypeName: standard

renderables:
  -
    renderingOptions:
      previousButtonLabel: 'previous Page'
      nextButtonLabel: 'next Page'
    type: Page
    identifier: page-1
    label: ''
    renderables:
      0:
        defaultValue: ''
        type: Hidden
        identifier: news_uid  # see below, how the news uid get's into the field...
        validators:
          -
            identifier: Integer
          -
            identifier: NotEmpty
      1:
        defaultValue: ''
        type: Hidden
        identifier: comments_count
        validators:
          -
            identifier: Integer
          -
            identifier: NotEmpty
      2:
        defaultValue: ''
        type: Textarea
        identifier: comment
        label: 'Comment'
        properties:
          fluidAdditionalAttributes:
            placeholder: 'Your comment'
            required: required
        validators:
          -
            identifier: NotEmpty
      3:
        defaultValue: ''
        type: Text
        identifier: name
        label: 'Your name'
        properties:
          fluidAdditionalAttributes:
            placeholder: 'Name'
            required: required
        validators:
          -
            identifier: NotEmpty

finishers:
  0:
    identifier: EmailToReceiver
    options:
      subject: 'New comment from {name}'
      recipientAddress: 'webmaster@example.com'
      recipientName: 'Webmaster'
      senderAddress: 'no-reply@example.com'
      senderName: 'Example Website'
      templatePathAndFilename: 'your_mail_path/new_comment.html' # This is an html email template for the info email, once a new comment has been submitted. See an example below
  1:
    identifier: SaveToDatabase
    options:
      0:
        table: tt_content                                # we save the comment into the tt_content table (as mentioned above, this is where you could hide the record as well in order to have a moderator accepting the comment - just add a "hidden: value: 1 " in the databaseColumnMappings section below)
        mode: insert
        databaseColumnMappings:
          pid:
            value: 80                                    # Create a system folder in the backend and place the pid here
          cType:
            value: textmedia
          date:
            value: '{__currentTimestamp}'
          tstamp:
            value: '{__currentTimestamp}'
          crdate:
            value: '{__currentTimestamp}'
          rowDescription:
            value: 'Comment for News with ID {news_uid}'
        elements:
          comment:
            mapOnDatabaseColumn: 'bodytext'
          name:
            mapOnDatabaseColumn: 'header'                # Please note that I save the name of the comment author into the header field, because it is more convenient in the backend. But you can choose basically any field
          news_uid:
            mapOnDatabaseColumn: 'tx_news_related_news'  # Here is where the news uid is inserted into the tt_content table to actually allow the comment to be related to the news entry
          comments_count:
            mapOnDatabaseColumn: 'sorting'               # We have to add the number of comments to have the comments showing up in the right order
      1:
        table: tx_news_domain_model_news                 # and update the news table to show the right number of content elements
        mode: update
        whereClause:
          uid: '{news_uid}'
        elements:
          comments_count:
            mapOnDatabaseColumn: 'content_elements'
  2:
    identifier: Redirect                                 # We have to reload the page, because otherwise the news isn't newly generated after clearing the cache (see below)
    options:
      pageUid: 83
      additionalParameters: 'tx_news_pi1[news]={news_uid}'			
```

As stated above, this is a really simple form definition. You can of course add further fields, as e.g., the comment authors email address or a more detailed name (first and last name or alias).

Now, let's quickly take a look at the mail template, which will be send to the webmaster or moderator or whoever suits you (filename: 'your_mail_path/new_comment.html' - this is nothing special, just the normal form template...):
```
{namespace formvh=TYPO3\CMS\Form\ViewHelpers}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="format-detection" content="telephone=no">
  </head>
  <body>
    <p>A new comment has been posted by {form.name} on news entry {form.news_uid}: "{form.comment}".</p>
  </body>
</html>
```

Next, we'll have to make sure, that the form values news_uid and the comment_count are properly filled upfront depending on which news detailed page the comment form is submitted. To do this add the following to your TS Template Setup:
```
# Comment form
lib.commentNumber = COA
lib.commentNumber{
    1 = TEXT
    1.dataWrap = DB:tx_news_domain_model_news:{GP:tx_news_pi1|news}:content_elements
    1.wrap3 = {|}
    1.insertData = 1
    2 = TEXT
    2.value = +1
    stdWrap.prioriCalc = 1
    stdWrap.intval = 1
}
# Set hidden values in new comment form
plugin.tx_form.settings.formDefinitionOverrides.news_comment.renderables.0.renderables {
  # Hidden value for news_uid
  0.defaultValue = TEXT
  0.defaultValue.data = GP:tx_news_pi1|news
  0.defaultValue.intval = 1
  # Hidden value for comments_count
  1.defaultValue < lib.commentNumber
}
```

Now, we have everything in place to put the comment form on the site. Add a new form content element within the Typo3 backend on the news detail page. I have it directly below the news extension record, so that the form shows up directly below the news entry and the comments, which will show up there in a minute. Within the form content element, select the comment.yaml form definition. If you open a detailed news page now, you should already see the form.

Excursus: This is, where you could make the commenting form accessible for logged-in users only. If you hide the form element for non-logged-in users, they won't be able to submit comments. Instead you could place a text element for non-logged-in users explaining them, that they have to log in in order to place a comment. If doing so, you should prefill the name (or and other additional fields) with the user data by amending the above TS snippet with 3.defaultValue = .... You could then hide the fields in the "renderables" section. Please note, that I have not yet tried this.

Now, let's take a look at the news templates to adjust the comment display. I use the following section within the Templates/Detail.html file. It is a very lean setup, but you can extend it as you wish. The Timeago is a nice JS solution to show the timestamp as elapsed time.
```
<f:if condition="{newsItem.contentElements}">
  <div class="comments_wrap">
	<h2>Comments</h2>
	<f:for each="{newsItem.contentElements}" as="element">
		<p>
		  <span class="comments_author">{element.header} </span>
		  <f:format.stripTags>{element.bodytext}</f:format.stripTags>
		  <span class="comment-time">(<span class="timeago">{f:format.date(date:element.crdate, format:'d. ')}<f:translate key="month.{f:format.date(date:element.crdate, format:'m')}" />{f:format.date(date:element.crdate, format:' Y, H:m')}</span>)</span>
		</p>
	</f:for>
  </div>
  <script src="fileadmin/tmpl/scripts/jquery.timeago.js" type="text/javascript"></script>
  <script language="javascript">jQuery(document).ready(function() {  jQuery(".timeago").timeago();});</script>
</f:if>
```

Within the list view, you can add the number of comments. To do so change the Partials/List/Item.html template and use the following snippet anywhere in the code. I have it after the "Read more" Link to have something like "Read more (3 comments).
```
<f:count>{newsItem.contentElements}</f:count>
```

Offcause, it is possible to place a condition round the comments count to show something else, if there isn't a comment yet:
```
<f:if condition="{newsItem.contentElements}">
  <f:then> (<f:count>{newsItem.contentElements}</f:count> comments)</f:then>
</f:if>
```
 
Finally, as mentioned right in the beginning, there still is an unsolved problem, where any support is highly valued! In order to clear the news elements cache after a new comment has been added, we have to add the following code at the end of function process() function in typo3/sysext/form/Classes/Domain/Finishers/SaveToDatabaseFinisher.php (the code must be executed as the last action within the process() function).
```
// Flush the cache of the news item after a comment has been submitted
$GP_tx_news = \TYPO3\CMS\Core\Utility\GeneralUtility::_GP('tx_news_pi1');
if(isset($GP_tx_news['news']) && ($GP_tx_news['news'] > 0)) // ensure that it is an integer > 0
{
	$cacheManager = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Core\\Cache\\CacheManager');
	$cacheManager->flushCachesByTag('tx_news_uid_'.$GP_tx_news['news']);
}
```

Please comment, if you have further suggestions! I would be most interesting in solutions how to 
- implement the cache clearing in an upgrade-safe manner
- sort the comments in the backend list view by date created by default

Best regards

@georgringer: As proposed feel free to add this to the documentation, if helpful. I still hope that there is a solution for the cache problem in future.

**Comment by georgringer** [comment]
thx btw for the issue, will keep in mind and maybe use for next project!

**Comment by typo3ua** [comment]
Hello, @HVStechnik !
What is new? Where can I see how it works online? Something changed in the your idea?

**Comment by typo3ua** [comment]
I did ...
Added to tt_content.php
```
<?php
defined('TYPO3_MODE') or die();
$fields = [
    'tt_contentfeuser_user' => [
        'exclude' => true,
        'label' => 'LLL:EXT:news_feuser/Resources/Private/Language/locallang.xlf:tx_news_domain_model_news.tx_newsfeuser_user',
        'config' => [
            'type' => 'group',
            'internal_type' => 'db',
            'allowed' => 'fe_users',
            'foreign_table' => 'fe_users',
            'size' => 10,
            'minitems' => 0,
            'maxitems' => 1010,
            'default' => '',
            'wizards' => [
                'suggest' => [
                    'type' => 'suggest',
                    'default' => [
                        'searchWholePhrase' => true
                    ]
                ],
            ],
        ]
    ]
];
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns('tt_content', $fields);
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes('tt_content', 'tt_contentfeuser_user', '', 'after:fe_group');
```
Added to ext_tables.sql
```
#
# Table structure for table 'tt_content'
#
CREATE TABLE tt_content (
  tt_contentfeuser_user varchar(100) DEFAULT '0' NOT NULL
);
```

**Comment by HVStechnik** [comment]
Hi @typo3ua,
I'm not quite sure, what you're trying to achieve. My goal is to setup a commenting system without any extension programming, but configuration of the news and form extension only. My above proposal is working for me. 
Regarding the cache clearing issue, an additional redirect finisher with a nocache URL parameter might solve the problem. This might be a better solution compared to the modification of the savetodatabase finisher. However, I haven't tried it so far.

**Comment by typo3ua** [comment]
I about the cache clearing issue,

The 'ext:news ' has hook for this `https://github.com/georgringer/news/blob/master/Classes/Hooks/DataHandler.php#L32-L44` but I still do not understand how to use.

**Comment by typo3ua** [comment]
There is only one solution, it needs to create a finisher. What I and did it.

### ClearCacheNewsFinisher.php
```
<?php
declare(strict_types = 1);
namespace T3UA\UkrainianPackage\Domain\Finishers;

use GeorgRinger\News\Hooks\DataHandler;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Form\Domain\Finishers\AbstractFinisher;

class ClearCacheNewsFinisher extends AbstractFinisher
{
    /**
     * @var array
     */
    protected $defaultOptions = [
        'getGlobalPostVar' => '',
        'getPidNewsRecord' => ''
    ];

    /**
     * Executes this finisher
     * @see AbstractFinisher::execute()
     *
     * @throws FinisherException
     */
    protected function executeInternal()
    {
        $finisherPidNewsRecord = $this->parseOption('getPidNewsRecord');
        $finisherGlobalPostVar = $this->parseOption('getGlobalPostVar');
        $this->newsUid = GeneralUtility::_GP($finisherGlobalPostVar);
        $insertedUid = $this->newsUid['uid'];
        if (empty($insertedUid)) {
            $insertedUid = $this->finisherContext->getFinisherVariableProvider()->get('SaveToDatabase', 'insertedUids.0');
        }
        $params = [
            'table' => 'tx_news_domain_model_news',
            'uid_page' => (int)$finisherPidNewsRecord,
            'uid' => (int)$insertedUid
        ];
        $cacheManager = GeneralUtility::makeInstance(DataHandler::class);
        $cacheManager->clearCachePostProc($params);
    }
}
```
### Setup.yaml
```
TYPO3:
  CMS:
    Form:
      prototypes:
        standard:
          finishersDefinition:
            ClearCacheNews:
              implementationClassName: 'T3UA\UkrainianPackage\Domain\Finishers\ClearCacheNewsFinisher'
```
### FormEditNews.form.yaml
```
finishers:
  -
    [...]
    identifier: EmailToReceiver
  -
    [...]
    identifier: SaveToDatabase
  -
    options:
      getGlobalPostVar: ''
      getPidNewsRecord: ''
    identifier: ClearCacheNews
  -
    [...]
    identifier: Redirect
renderables:
```
### Depends
TYPO3 9.5.9
NEWS version 7.3.xx
