### ISSUE TITLE
Pagination - root page / sub page

### ISSUE THREAD

**Issue by zelcode** [georgringer/news#774]
## Bug Report
This is maybe Core related, there is issue https://forge.typo3.org/issues/86588

**Current Behavior**
News list pagination doesn't work on root page, you get
#1518472189 TYPO3\CMS\Core\Error\Http\PageNotFoundException

Page tree:

Home [root page, id=1]
Home [shortcut to root page, id=2]
Shop [id=3]

``` yaml
NewsPagination:
  type: Extbase
  limitToPages:
    - 1
    - 3
  extension: News
  plugin: Pi1
  routes:
    -
      routePath: 'p-{page}'
      _controller: 'News::list'
      _arguments:
        page: '@widget_0/currentPage'
  defaultController: 'News::list'
  defaults:
    page: '0'
  requirements:
    page: \d+
  aspects:
    page:
      type: StaticRangeMapper
      start: '1'
      end: '100'
```
On subpage Shop news list pagination works, but with one exception,
if you are on page 2-to-any then go to first paginated page, link looks like this (and goes to page Shop):

http://localhost:3000/shop?tx_news_pi1[action]=list&tx_news_pi1[controller]=News&cHash=e910af50fb7b2ed8f1bfcd485ef2248d

instead it should look like this:

http://localhost:3000/shop

Link to any page but first look good and work (http://localhost:3000/shop/p-3).

**Expected behavior/output**
Pagination should work.

**Environment**
- TYPO3 version(s): 9.5.0
- news version: 7.0.6
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux Mint 18.3, Nginx

**Comment by georgringer** [comment]
Core issue and imo Already on forge. Wanna share your full config still?

**Comment by typo3ua** [comment]
...it is my example for ext:news
```
routeEnhancers:
  NewsPlugin:
    type: Extbase
    limitToPages:
      - 2
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/page/{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
    defaultController: 'News::list'
    defaults:
      page: '0'
    requirements:
      page: '\d+'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
  CategoryListNews:
    type: Extbase
    limitToPages:
      - 2
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/category/{category_title}'
        _controller: 'News::list'
        _arguments:
          category_title: 'overwriteDemand/categories'
    defaultController: 'News::list'
    aspects:
      category_title:
        type: PersistedAliasMapper
        tableName: 'sys_category'
        routeFieldName: 'title'
  TagListNews:
    type: Extbase
    limitToPages:
      - 2
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/category/{tag_title}'
        _controller: 'News::list'
        _arguments:
          tag_title: 'overwriteDemand/tags'
    defaultController: 'News::list'
    aspects:
      tag_title:
        type: PersistedAliasMapper
        tableName: 'tx_news_domain_model_tag'
        routeFieldName: 'title'
  NewsDetail:
    type: Extbase
    limitToPages:
      - 3
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
    defaultController: 'News::detail'
    aspects:
      news_title:
        type: PersistedAliasMapper
        tableName: 'tx_news_domain_model_news'
        routeFieldName: 'path_segment'
```
... but still has some problems with route path
 - converting 'routeFieldName' to lowercase?
 - converting 'routeFieldName' from Cyrillic to Latin?
 - pagination
