### ISSUE TITLE
Typo3 9.5.x and the new routing stuff

### ISSUE THREAD

**Issue by chequille** [georgringer/news#956]
Hi Everybody,

currently playing around to migrate my current Typo3 8.x.x site to Typo3 9.
So far with a few modifikations everything works as before.

But only with ugly looking page links.
So I had a look into the Site Configuration stuff which is working as it should so far.
ANd I was happy to find as well some configuration examples for the YAML file for the News Extension.

I tried it and I found the following:
I have on the same site two category selected entries and one date menu. ANd of course on entry for the results. This is working fine and I get my news as I seleceted them.

Now I tried the Basic Exmple as of the News Manual and inserted it into the yaml file.
After this, my categorie selection parts work with the expected looking "...../programm/aktuelles f.e. and when clicking on it, I get the list of the news matching the category.

But now I tried to add the DateMenu Example as of the manual and put that as well into the yaml file.

Result is, that all links look good  (.../programm/2019/maerz and for categories .../programm/aktuelles), but only clicking on a date menu entry I get results. When clicking on a category in my category selection I get no results with an error page not found.

Does somebody have an idea why it is not working together? The yaml file looks like this:
```
rootPageId: 1
base: 'https://ho8.demo/'
baseVariants: {  }
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: 'https://ho8.demo/'
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: de
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=110'
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n"
routeEnhancers:
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      -
        routePath: '/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      -
        routePath: '/{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      tag-name:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_tag
        routeFieldName: slug
  DateMenu:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
        requirements:
          page: \d+
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      -
        routePath: '/{date-year}'
        _controller: 'News::list'
        _arguments:
          date-month: overwriteDemand/month
          date-year: overwriteDemand/year
          page: '@widget_0/currentPage'
        requirements:
          date-year: \d+
      -
        routePath: '/{date-year}/page-{page}'
        _controller: 'News::list'
        _arguments:
          date-year: overwriteDemand/year
          page: '@widget_0/currentPage'
        requirements:
          date-year: \d+
          page: \d+
      -
        routePath: '/{date-year}/{date-month}'
        _controller: 'News::list'
        _arguments:
          date-month: overwriteDemand/month
          date-year: overwriteDemand/year
          page: '@widget_0/currentPage'
        requirements:
          date-month: \d+
          date-year: \d+
      -
        routePath: '/{date-year}/{date-month}/page-{page}'
        _controller: 'News::list'
        _arguments:
          date-month: overwriteDemand/month
          date-year: overwriteDemand/year
          page: '@widget_0/currentPage'
        requirements:
          date-month: \d+
          date-year: \d+
          page: \d+
    defaultController: 'News::list'
    defaults:
      page: '0'
      date-month: ''
      date-year: ''
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '25'
      date-month:
        type: StaticValueMapper
        map:
          januar: '01'
          februar: '02'
          maerz: '03'
          april: '04'
          mai: '05'
          juni: '06'
          juli: '07'
          august: '08'
          september: '09'
          oktober: '10'
          november: '11'
          dezember: '12'
      date-year:
        type: StaticRangeMapper
        start: '2000'
        end: '2030'

```
